### ISSUE TITLE
Idea/Name

### ISSUE THREAD

**Issue by dalefrancis88** [dashed/redux-lens#4]
Hey, I had a very similiar idea to you it seems. Although it looks like you're no longer working on this. Are you open to the idea of me taking over this project and name?

**Comment by dashed** [comment]
@dalefrancis88 Yep, I'm still maintaining this. You should totally publish your version of the idea (even though it's similar). 😃

**Comment by dalefrancis88** [comment]
The trouble is i like the name, i can't really think of another name :/

**Comment by dalefrancis88** [comment]
it's been two years, any chance now?

**Comment by dashed** [comment]
@dalefrancis88 sure. please email me the npm username you'd like `redux-lens` be transferred to at mailforalberto@gmail.com

I'll have it transferred over the weekend.

**Comment by dalefrancis88** [comment]
shot you an email

**Comment by dashed** [comment]
Transferred
